### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by zouhongwei** [Liusifei/pytorch_spn#3]
when i use your code, the GPU memory keep increasing during training, and then out of memory, but it works well during test, can you help me?

**Comment by ZhangC2** [comment]
I have the same problem

**Comment by sunshineatnoon** [comment]
@zouhongwei @ZhangC2 you can try earlier version of pytorch, the one I tried and worked is `torch==0.4.0a0+059299b`. Also pytorch 0.3.0 should work.

**Comment by ZhangC2** [comment]
@sunshineatnoon thanks，it works。

**Comment by zouhongwei** [comment]
@sunshineatnoon yeah, it works. But I checked the code, and add some code in gaterecurrent2dnoind.py as follow, and the problem resolved!Anyway, thank you very much~
```python
def backward(self, grad_output):
        assert(self.hiddensize is not None and grad_output.is_cuda)
        num, channels, height, width = self.hiddensize

        grad_X = torch.zeros(num, channels, height, width, requires_grad=False).cuda().data
        grad_G1 = torch.zeros(num, channels, height, width, requires_grad=False).cuda().data
        grad_G2 = torch.zeros(num, channels, height, width, requires_grad=False).cuda().data
        grad_G3 = torch.zeros(num, channels, height, width, requires_grad=False).cuda().data

        gaterecurrent2d.gaterecurrent2dnoind_backward_cuda(self.horizontal, self.reverse, self.output, grad_output, self.X, self.G1, self.G2, self.G3, grad_X, grad_G1, grad_G2, grad_G3)

        del self.hiddensize 
        del self.G1
        del self.G2
        del self.G3
        del self.output
        del self.X

        return grad_X, grad_G1, grad_G2, grad_G3
```

**Comment by fengmeixue** [comment]
> @zouhongwei @ZhangC2 you can try earlier version of pytorch, the one I tried and worked is `torch==0.4.0a0+059299b`. Also pytorch 0.3.0 should work.

What version of python are you using?
